# Generated by Django 3.0.3 on 2020-02-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
