# Generated by Django 3.0.3 on 2020-02-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='related_note',
            field=models.ManyToManyField(related_name='_notes_related_note_+', to='main.Notes'),
        ),
    ]
