# Generated by Django 3.0.3 on 2020-02-26 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notes_related_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='topics',
            name='parent_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Topics'),
        ),
    ]
