# Generated by Django 3.0.3 on 2020-02-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=150)),
                ('parent_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topics')),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('part_of_speech', models.CharField(max_length=20)),
                ('definition', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topics')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('parent_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Notes')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topics')),
            ],
        ),
    ]
