# Generated by Django 3.0.3 on 2020-02-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200226_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='related_note',
            field=models.ManyToManyField(null=True, related_name='_notes_related_note_+', to='main.Notes'),
        ),
    ]
