# Generated by Django 3.0.3 on 2020-02-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200226_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notes',
            name='related_note',
            field=models.ManyToManyField(related_name='_notes_related_note_+', to='main.Notes'),
        ),
    ]
