# Generated by Django 3.0.3 on 2020-02-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200226_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='definition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
